In [42]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory




In [43]:
train = pd.read_csv('train.csv')
#test = pd.read_csv('test.csv')

In [44]:
train.info()
train.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 23 columns):
Choice                 5500 non-null int64
A_follower_count       5500 non-null int64
A_following_count      5500 non-null int64
A_listed_count         5500 non-null int64
A_mentions_received    5500 non-null float64
A_retweets_received    5500 non-null float64
A_mentions_sent        5500 non-null float64
A_retweets_sent        5500 non-null float64
A_posts                5500 non-null float64
A_network_feature_1    5500 non-null int64
A_network_feature_2    5500 non-null float64
A_network_feature_3    5500 non-null float64
B_follower_count       5500 non-null int64
B_following_count      5500 non-null int64
B_listed_count         5500 non-null int64
B_mentions_received    5500 non-null float64
B_retweets_received    5500 non-null float64
B_mentions_sent        5500 non-null float64
B_retweets_sent        5500 non-null float64
B_posts                5500 non-null float64
B_network

Choice  A_follower_count  A_following_count  A_listed_count  \
0       0               228                302               3   
1       0             21591               1179             228   
2       0              7310               1215             101   
3       0                20                  7               2   
4       1             45589                862            2641   
5       0            285735             276251            3417   
6       0            285735             276251            3417   
7       1              9512                 12             213   
8       1           2273871               4524           11946   
9       0            182598               1402            3831   

   A_mentions_received  A_retweets_received  A_mentions_sent  A_retweets_sent  \
0             0.583979             0.100503         0.100503         0.100503   
1            90.456506            25.798292         5.709329         1.111159   
2            25.503644             9.556347         5.361519         0.591206   
3             7.690824             0.277306         1.331508         0.100503   
4           148.854279            36.998884        27.881768         3.333492   
5            19.327582             7.292016         0.100503         0.100503   
6            19.327582             7.292016         0.100503         0.100503   
7            52.167068            23.182288         0.362150         0.100503   
8          6782.405338          2944.524245        12.955723         2.791861   
9           145.844910            74.002958        23.549189         0.100503   

     A_posts  A_network_feature_1  ...  B_following_count  B_listed_count  \
0   0.362150                    2  ...              29808            1689   
1   5.176620                  369  ...                848            1610   
2   3.589718                   95  ...                482             206   
3   2.830627                    6  ...              17637             278   
4  23.861282                  551  ...               1711             181   
5   0.100503                   60  ...               1500             474   
6   0.100503                   60  ...               1001           15117   
7   6.806045                  195  ...                710             959   
8  66.206208                21678  ...                551            6209   
9  15.953243                  567  ...               1299            9950   

   B_mentions_received  B_retweets_received  B_mentions_sent  B_retweets_sent  \
0            15.430498             3.984029         8.204331         0.332423   
1            40.495021             8.943607         3.227677         0.564343   
2             0.734696             0.354379         0.603202         0.100503   
3           572.874856           390.293681        27.552040         7.167557   
4            21.601866             3.581661         6.764657         1.119727   
5            40.592512             5.923009        19.648064         1.861765   
6           266.013874            54.345230        13.111904         0.334766   
7             7.368643             2.088375         1.598798         0.595812   
8           493.256379           206.660552         4.115212         0.854539   
9           189.755230            67.310223        11.294831         2.567269   

     B_posts  B_network_feature_1  B_network_feature_2  B_network_feature_3  
0   6.988815                   66            75.530303          1916.893939  
1   1.070321                  163           132.030675          2931.515337  
2   0.603202                    3            10.333333           277.333333  
3  32.101906                 1762            23.469296          1395.845634  
4   4.563246                   85            48.500000          1993.627907  
5  12.261029                  128           107.431818          2481.136364  
6  13.665173                  928           172.986229          5321.646186  
7   1.332849        

In [45]:
display(train[["Choice","A_follower_count","A_posts",]].groupby(["Choice","A_follower_count"]).agg(["min",'mean',"max"]).style.background_gradient(cmap="autumn"))

In [10]:
print("Any missing sample in training set:",train.isnull().values.any())
print("Any missing sample in test set:",test.isnull().values.any(), "\n")

Any missing sample in training set: False
Any missing sample in test set: False 



In [46]:
train_outcome = pd.crosstab(index=train["Choice"],  # Make a crosstab
                              columns="count")      # Name the count column

train_outcome

col_0   count
Choice       
0        2698
1        2802

In [56]:
#Select feature column names and target variable we are going to use for training
#features=['A_follower_count','A_listed_count','A_mentions_received','A_retweets_received','A_posts','A_network_feature_1','A_network_feature_2','A_network_feature_3','B_follower_count','B_following_count','B_listed_count','B_mentions_received','B_retweets_received','B_posts','B_network_feature_1','B_network_feature_2','B_network_feature_3']
features=train.columns
target = 'Choice'
#This is input which our classifier will use as an input.
train[features].head(10)

Choice  A_follower_count  A_following_count  A_listed_count  \
0       0               228                302               3   
1       0             21591               1179             228   
2       0              7310               1215             101   
3       0                20                  7               2   
4       1             45589                862            2641   
5       0            285735             276251            3417   
6       0            285735             276251            3417   
7       1              9512                 12             213   
8       1           2273871               4524           11946   
9       0            182598               1402            3831   

   A_mentions_received  A_retweets_received  A_mentions_sent  A_retweets_sent  \
0             0.583979             0.100503         0.100503         0.100503   
1            90.456506            25.798292         5.709329         1.111159   
2            25.503644             9.556347         5.361519         0.591206   
3             7.690824             0.277306         1.331508         0.100503   
4           148.854279            36.998884        27.881768         3.333492   
5            19.327582             7.292016         0.100503         0.100503   
6            19.327582             7.292016         0.100503         0.100503   
7            52.167068            23.182288         0.362150         0.100503   
8          6782.405338          2944.524245        12.955723         2.791861   
9           145.844910            74.002958        23.549189         0.100503   

     A_posts  A_network_feature_1  ...  B_following_count  B_listed_count  \
0   0.362150                    2  ...              29808            1689   
1   5.176620                  369  ...                848            1610   
2   3.589718                   95  ...                482             206   
3   2.830627                    6  ...              17637             278   
4  23.861282                  551  ...               1711             181   
5   0.100503                   60  ...               1500             474   
6   0.100503                   60  ...               1001           15117   
7   6.806045                  195  ...                710             959   
8  66.206208                21678  ...                551            6209   
9  15.953243                  567  ...               1299            9950   

   B_mentions_received  B_retweets_received  B_mentions_sent  B_retweets_sent  \
0            15.430498             3.984029         8.204331         0.332423   
1            40.495021             8.943607         3.227677         0.564343   
2             0.734696             0.354379         0.603202         0.100503   
3           572.874856           390.293681        27.552040         7.167557   
4            21.601866             3.581661         6.764657         1.119727   
5            40.592512             5.923009        19.648064         1.861765   
6           266.013874            54.345230        13.111904         0.334766   
7             7.368643             2.088375         1.598798         0.595812   
8           493.256379           206.660552         4.115212         0.854539   
9           189.755230            67.310223        11.294831         2.567269   

     B_posts  B_network_feature_1  B_network_feature_2  B_network_feature_3  
0   6.988815                   66            75.530303          1916.893939  
1   1.070321                  163           132.030675          2931.515337  
2   0.603202                    3            10.333333           277.333333  
3  32.101906                 1762            23.469296          1395.845634  
4   4.563246                   85            48.500000          1993.627907  
5  12.261029                  128           107.431818          2481.136364  
6  13.665173                  928           172.986229          5321.646186  
7   1.332849        

In [57]:
train[target].head(10).values

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

In [50]:
from sklearn.ensemble import RandomForestClassifier

# We define the model
rfcla = RandomForestClassifier(n_estimators=100,random_state=168,n_jobs=-1)

# We train model
rfcla.fit(train[features],train[target])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=168, verbose=0, warm_start=False)

In [51]:
predictions = rfcla .predict(test[features])

#Display our predictions
predictions

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [58]:
#Preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score # to split the data
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, fbeta_score #To evaluate our model

from sklearn.model_selection import GridSearchCV

# Algorithmns models to be compared
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [59]:
print(train[features].shape)
print(train[target].shape)
#print(test[target].shape)

(5500, 23)
(5500,)


In [60]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, fbeta_score #To evaluate our model

from sklearn.model_selection import GridSearchCV
X=train[features]
y=train[target]
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=42)
# to feed the random state
seed = 7

# prepare models
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('RF', RandomForestClassifier()))
models.append(('SVM', SVC(gamma='auto')))
#models.append(('XGB', XGBClassifier()))

# evaluate each model in turn
results = []
names = []
scoring = 'recall'

for name, model in models:
        kfold = KFold(n_splits=10, random_state=seed)
        cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
        results.append(cv_results)
        names.append(name)
        model = model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
        print(msg)
        print(accuracy_score(y_test,y_pred))
        print("\n")
        print(confusion_matrix(y_test, y_pred))
        print("\n")
        print(classification_report(y_test, y_pred))

(5500, 23)
(5500,)
LR: 0.769631 (0.028532)
0.744


[[482 197]
 [155 541]]


             precision    recall  f1-score   support

          0       0.76      0.71      0.73       679
          1       0.73      0.78      0.75       696

avg / total       0.74      0.74      0.74      1375



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anacond

LDA: 0.750422 (0.023982)
0.7076363636363636


[[445 234]
 [168 528]]


             precision    recall  f1-score   support

          0       0.73      0.66      0.69       679
          1       0.69      0.76      0.72       696

avg / total       0.71      0.71      0.71      1375

KNN: 0.761385 (0.033819)
0.7338181818181818


[[471 208]
 [158 538]]


             precision    recall  f1-score   support

          0       0.75      0.69      0.72       679
          1       0.72      0.77      0.75       696

avg / total       0.73      0.73      0.73      1375

CART: 1.000000 (0.000000)
1.0


[[679   0]
 [  0 696]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00       679
          1       1.00      1.00      1.00       696

avg / total       1.00      1.00      1.00      1375

NB: 0.937351 (0.029049)
0.5563636363636364


[[106 573]
 [ 37 659]]


             precision    recall  f1-score   support

          0       0.74      0.16

In [34]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.5090343727252721

In [41]:

from sklearn.metrics import roc_auc_score, roc_curve
threshold = 0.5
y_pred = y_pred_proba >= threshold
fpr, tpr, thresholds = roc_curve(y_train, y_pred_proba)
plt.plot(fpr, tpr)
plt.title('ROC curve')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
print('Area under the Receiver Operating Characteristic curve:', 
      roc_auc_score(y_train, y_pred_proba))
    
# When threshold = 0.5
false_positives = 452
true_positives = 860
false_positive_rate = false_positives/actual_negative
true_positive_rate = true_positives/actual_positive
plt.scatter(false_positive_rate, true_positive_rate)
# When threshold = 0.1
false_positives = 5267
true_positives = 2418
false_positive_rate = false_positives/actual_negative
true_positive_rate = true_positives/actual_positive
plt.scatter(false_positive_rate, true_positive_rate);




NameError: name 'y_pred_proba' is not defined